<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-12-17T17:29:04 IST" name="Default suite" finished-at="2019-12-17T17:29:37 IST" duration-ms="32897">
    <groups>
    </groups>
    <test started-at="2019-12-17T17:29:04 IST" name="Default test" finished-at="2019-12-17T17:29:37 IST" duration-ms="32897">
      <class name="TESTNGG.AssertionConcept">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TESTNGG.AssertionConcept@2d710f1a]" started-at="2019-12-17T17:29:04 IST" name="setUp" finished-at="2019-12-17T17:29:18 IST" duration-ms="14481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="softAssertTest()[pri:1, instance:TESTNGG.AssertionConcept@2d710f1a]" started-at="2019-12-17T17:29:18 IST" name="softAssertTest" finished-at="2019-12-17T17:29:18 IST" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- softAssertTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TESTNGG.AssertionConcept@2d710f1a]" started-at="2019-12-17T17:29:18 IST" name="tearDown" finished-at="2019-12-17T17:29:20 IST" duration-ms="1414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:TESTNGG.AssertionConcept@2d710f1a]" started-at="2019-12-17T17:29:20 IST" name="setUp" finished-at="2019-12-17T17:29:35 IST" duration-ms="15421" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="hardAssertTest()[pri:2, instance:TESTNGG.AssertionConcept@2d710f1a]" started-at="2019-12-17T17:29:35 IST" name="hardAssertTest" finished-at="2019-12-17T17:29:35 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at TESTNGG.AssertionConcept.hardAssertTest(AssertionConcept.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hardAssertTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TESTNGG.AssertionConcept@2d710f1a]" started-at="2019-12-17T17:29:35 IST" name="tearDown" finished-at="2019-12-17T17:29:37 IST" duration-ms="1437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TESTNGG.AssertionConcept -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
